### ISSUE TITLE
Test Failures Against Boulder Product Development Image:  "os_ready-BIGIP-12.1.0.1.0.1447"

### ISSUE THREAD

**Issue by zancas** [F5Networks/f5-common-python#842] opened 2016-12-13 20:09 UTC
Folks I run the following command:

```BASH
py.test -v --bigip REDACTED --username REDACTED --password REDACTED --release 12.1.0 --ignore=f5/bigip/tm/asm --ignore=f5/bigip/tm/gtm --tb=no . | grep FAILED
```

Against the image mentioned in the issue title.

The first time I run I get this output:

```
f5/bigip/tm/ltm/test/functional/test_profile.py::TestClassification::test_RUL FAILED
f5/bigip/tm/ltm/test/functional/test_profile.py::TestSmtp::test_MCURDL_11_6_and_greater FAILED
f5/bigip/tm/ltm/test/functional/test_profile.py::TestWebSecurity::test_load FAILED
f5/bigip/tm/util/test/functional/test_qkview.py::test_command_result_present FAILED
f5/bigip/tm/util/test/functional/test_qkview.py::test_invalid_option_for_qkview FAILED
```

on *subsequent* runs there's an additional failure:

```
f5/bigip/tm/sys/test/functional/test_ucs.py::TestUcs::test_ucs_LR FAILED
```

**Comment by zancas** [comment] 2016-12-13 20:10
@pjbreaux @caphrim007 it seems plausible that the fails are due to a different version of 12.1.0 than what we're running in Jenkins.

Assuming that the Jenkins runs are running clean, I don't believe this is very high priority.

**Comment by wojtek0806** [comment] 2016-12-15 16:38
i do not get those failures and i am testing against public ISOs

**Comment by wojtek0806** [comment] 2017-01-09 13:35
The UCS TEST failure is caused by the fact that we save UCS file but do not remove it, as there is an issue with UCS removal via REST, you have to do this manually, or use util/bash and run tmsh command to remove it. Which is what we could do in the said tests.

**Comment by wojtek0806** [comment] 2017-01-09 13:35
Those tests are module dependant:

f5/bigip/tm/ltm/test/functional/test_profile.py::TestClassification::test_RUL FAILED
f5/bigip/tm/ltm/test/functional/test_profile.py::TestSmtp::test_MCURDL_11_6_and_greater FAILED
f5/bigip/tm/ltm/test/functional/test_profile.py::TestWebSecurity::test_load FAILED

**Comment by wojtek0806** [comment] 2017-01-09 13:36
I would need to see the stacktrace for those:

f5/bigip/tm/util/test/functional/test_qkview.py::test_command_result_present FAILED
f5/bigip/tm/util/test/functional/test_qkview.py::test_invalid_option_for_qkview FAILED

But I suspect one of them could be due to the time it takes to generate qkview on hardware unit. Just guessing here

**Comment by wojtek0806** [comment] 2017-01-23 09:58
@zancas or @pjbreaux what is the status of this? can we close this issue?

**Comment by wojtek0806** [comment] 2017-03-17 16:54
closing

**Closed as completed by wojtek0806** 2017-03-17 16:54 UTC
Labels: bug, 12.1.0
