### ISSUE TITLE
Adding a policy to a virtual on 12.1.1 produces 404, but succeeds in adding anyway

### ISSUE THREAD

**Issue by pjbreaux** [F5Networks/f5-common-python#833] opened 2016-11-23 16:25 UTC
When adding an LTM policy to a virtual server on TMOS version BIG-IP 12.1.1 Build 2.0.204 Hotfix HF2, a 404 error is returned to the client, but the policy is added anyway. I successfully reproduced this against an 12.1.1 box with Postman.

```POST to https://10.190.7.221/mgmt/tm/ltm/virtual/~Project_e43b44cb2a22431f8c0de68e9349fc11~Project_d3447d86-7d57-47fe-bd7e-cea44c390316/policies```

with JSON:

```{"partition": "Project_e43b44cb2a22431f8c0de68e9349fc11", "name": "wrapper_policy"}```

Return is:

```
{
  "code": 404,
  "message": "Object not found - wrapper_policy",
  "errorStack": [],
  "apiError": 1
}
```
```GET to https://10.190.7.221/mgmt/tm/ltm/virtual/~Project_e43b44cb2a22431f8c0de68e9349fc11~Project_d3447d86-7d57-47fe-bd7e-cea44c390316/policies```

Returns:
```
{
  "kind": "tm:ltm:virtual:policies:policiescollectionstate",
  "selfLink": "https://localhost/mgmt/tm/ltm/virtual/~Project_e43b44cb2a22431f8c0de68e9349fc11~Project_d3447d86-7d57-47fe-bd7e-cea44c390316/policies?ver=12.1.1",
  "items": [
    {
      "kind": "tm:ltm:virtual:policies:policiesstate",
      "name": "wrapper_policy",
      "partition": "Project_e43b44cb2a22431f8c0de68e9349fc11",
      "fullPath": "/Project_e43b44cb2a22431f8c0de68e9349fc11/wrapper_policy",
      "generation": 2069,
      "selfLink": "https://localhost/mgmt/tm/ltm/virtual/~Project_e43b44cb2a22431f8c0de68e9349fc11~Project_d3447d86-7d57-47fe-bd7e-cea44c390316/policies/~Project_e43b44cb2a22431f8c0de68e9349fc11~wrapper_policy?ver=12.1.1"
    }
  ]
}
```

**Comment by wojtek0806** [comment] 2016-11-23 18:50
why am i not surprised :) found this issue on two endpoints in GTM. Feel free to look at create method in Gtm Pools

**Comment by wojtek0806** [comment] 2017-02-06 14:11
Unless this is a regression it should work.

I have POSTed with this JSON on 12.1.0 HF1 to "/mgmt/tm/ltm/virtual/\~Common\~testy/policies/" :
````
{"name":"bugtest", "partition":"Common"}
````
and i got 200 OK:
````
{
  "kind": "tm:ltm:virtual:policies:policiesstate",
  "name": "bugtest",
  "fullPath": "bugtest",
  "generation": 26295,
  "selfLink": "https://localhost/mgmt/tm/ltm/virtual/~Common/~testy/policies/bugtest?ver=12.1.0"
}

````
My policy was published, I only got 404 when i tried to attach DRAFT policy:

````
{
  "code": 404,
  "message": "01020036:3: The requested policy (bugfix) was not found.",
  "errorStack": [],
  "apiError": 3
}
````

**Comment by wojtek0806** [comment] 2017-02-06 14:17
Given that we do not officially support 12.1.1, I am going to test on 12.1.2 (which should be the version that we go to due to large number of fixes)

**Comment by wojtek0806** [comment] 2017-02-08 11:58
This works fine in 12.1.2:

````

{
  "kind": "tm:ltm:virtual:policies:policiesstate",
  "name": "bugtest",
  "fullPath": "bugtest",
  "generation": 1642,
  "selfLink": "https://localhost/mgmt/tm/ltm/virtual/~Common~testy/policies/bugtest?ver=12.1.2"
}

````

This issue seems to be isolated to 12.1.1 only, given that we are not going beyond 12.1.0 (and it works there), what do you want to do with it?

I vote for leaving this as it is (unless there is a compelling need to stay in 12.1.1 and not go to 12.1.2 ,which it shouldn't), and closing this ticket. I will focus on fixing 11.5.4

@pjbreaux @zancas @caphrim007

**Comment by wojtek0806** [comment] 2017-02-12 17:40
Fixed

**Closed as completed by wojtek0806** 2017-02-12 17:40 UTC
Labels: bug, functional test
