### ISSUE TITLE
members_s and members code examples in docs aren't working

### ISSUE THREAD

**Issue by jputrino** [F5Networks/f5-common-python#419] opened 2016-05-13 21:29 UTC
Errors are returned when you try to follow the `members_s` and `members` code examples.
http://f5-sdk.readthedocs.io/en/v0.1.6/userguide/ltm_pools_members_code_example.html

We need to troubleshoot and correct the examples. ( looking at @zancas )

**Comment by caphrim007** [comment] 2016-05-17 18:55
@jputrino this is being caused by the expectation by the example that pools have a description by default. I'm not sure which version of BIG-IP you're verifying this on, but on 12.0.0 0.0.606 this assumption is False.

**Comment by caphrim007** [comment] 2016-05-17 19:10
@jputrino i guess that was just one of the problems. now I see the one you're talking about. Looking

**Comment by caphrim007** [comment] 2016-05-17 19:22
@jputrino Is this the error you're referring to?

``` python
Text: u'{"code":404,"message":"01020036:3: The requested node (/Common/m1) was not
found.","errorStack":[]}'
```

**Comment by wojtek0806** [comment] 2016-05-19 09:18
Issue Review: Would need the exact error here to determine root cause.

**Comment by jputrino** [comment] 2016-05-19 15:40
@caphrim007 @wojtek0806 -- I'm on BIG-IP 11.6. The error @caphrim007 provided above is the one I'm getting when I try to create a pool member. I don't currently have any members configured on my BIG-IP. Thanks!

**Comment by zancas** [comment] 2016-05-19 15:43
@jputrino Is this issue resolved?

**Comment by jputrino** [comment] 2016-05-19 16:05
@zancas - I'm trying it out again now, after fetching, rebasing, and updating the requirements. I wanted to verify the error first.

**Comment by jputrino** [comment] 2016-05-19 16:41
Still not working. Here's the traceback:

```
Traceback (most recent call last):
  File "docs/userguide/code_example.py", line 46, in <module>
    m1 = pool_1.members_s.members.create(partition='Common', name='m1:80')
  File "/Users/putrino/openstack/f5-common-python/f5/bigip/resource.py", line 713, in create
    self._create(**kwargs)
  File "/Users/putrino/openstack/f5-common-python/f5/bigip/resource.py", line 667, in _create
    response = session.post(_create_uri, json=kwargs, **requests_params)
  File "/Users/putrino/openstack/f5-common-python/venv/lib/python2.7/site-packages/icontrol/session.py", line 254, in wrapper
    raise iControlUnexpectedHTTPError(error_message, response=response)
icontrol.session.iControlUnexpectedHTTPError: 404 Unexpected Error: Not Found for uri: https://10.190.7.161:443/mgmt/tm/ltm/pool/~Common~pool1/members/
Text: u'{"code":404,"message":"01020036:3: The requested node (/Common/m1) was not found.","errorStack":[]}'
```

Here's the full code example I'm using:

```
from f5.bigip import ManagementRoot

# Connect to the BigIP and configure the basic objects
mgmt = ManagementRoot('10.190.7.161', 'admin', 'admin')
ltm = mgmt.tm.ltm
pools = mgmt.tm.ltm.pools
pool = mgmt.tm.ltm.pools.pool

# Create a pool
pool1 = mgmt.tm.ltm.pools.pool.create(name='pool1', partition='Common')

# Define a pool object and load an existing pool
pool_obj = mgmt.tm.ltm.pools.pool
pool_1 = pool_obj.load(partition='Common', name='pool1')

# We can also skip creating the object and load the pool directly
pool_2 = mgmt.tm.ltm.pools.pool.load(partition='Common', name='pool1')

# Make sure 1 and 2 have the same names and generation
assert pool_1.name == pool_2.name
assert pool_1.generation == pool_2.generation

print pool_1.name
print pool_2.name
print pool_1.generation
print pool_2.generation


# Update the pool description
pool_1.description = "This is my first pool"
pool_1.update()

# Check the updated description
print pool_1.description

# Refresh pool_2 and check that is now equal
pool_2.refresh()
print pool_2.description
print pool_1.generation
print pool_2.generation

# Create members on pool_1
members = pool_1.members_s
member = pool_1.members_s.members

m1 = pool_1.members_s.members.create(partition='Common', name='m1:80')
m2 = pool_1.members_s.members.create(partition='Common', name='m2:80')

# load the pool members
m1 = pool_1.members_s.members.load(partition='Common', name='m1:80')
m2 = pool_1.members_s.members.load(partition='Common', name='m2:80')

# Get all of the pool members for pool_1 and print their names
for member in members:
    print member.name

# Delete our pool member m1
m1.delete()

# Make sure it is gone
if pool_1.members_s.members.exists(partition='Common', name='m1:80'):
    raise Exception("Object should have been deleted")

# We are done with this pool so remove it from BIG-IP
pool_1.delete()

# Make sure it is gone
if mgmt_rt.tm.ltm.pools.pool.exists(partition='Common', name='mypool'):
    raise Exception("Object should have been deleted")
```

**Comment by caphrim007** [comment] 2016-05-19 17:42
@jputrino @zancas this is caused because the Node associated with the pool member does not exist. Note the error

`The requested node (/Common/m1) was not found`

You need to create the node before you can assign it to a pool member, and as you'll note in the code, there is no node being created.

**Comment by caphrim007** [comment] 2016-05-19 17:42
the better question is "how did this _ever_ work?"

**Comment by wojtek0806** [comment] 2016-05-22 22:22
Sorry to butt in but I think you are testing this agains  vanilla 11.6 am i correct?  I have found something related i think you should be aware of: SOL16170

**Closed as completed** 2016-07-06 16:25 UTC
Labels: bug, help wanted, documentation
