### ISSUE TITLE
Where to go for basic help?

### ISSUE THREAD

**Issue by KDaveC** [F5Networks/f5-common-python#869] opened 2017-01-05 22:50 UTC
I'm new to Python and installed the SDK for F5. I tried a few examples to learn by and most won't work.
The example to get pools works fine but I tried the create and load examples and both throw errors. Using ver. 11.5.1 on the LTM, Python 3.6 and the latest SDK. Am I missing something and is there a better place to go to ask questions?

As an example this works fine.
pool_collection = mgmt.tm.ltm.pools.get_collection()
pools = mgmt.tm.ltm.pools
for pool in pool_collection:
     print (pool.name)

This throws errors.
mypool = mgmt.tm.ltm.pools.pool.create(name='mypool' , partition='Common')

Thank you,
Dave

**Comment by caphrim007** [comment] 2017-01-05 22:54
@KDaveC what's the error you're receiving?

**Comment by KDaveC** [comment] 2017-01-06 13:53
Here's the code I'm trying.
import requests

from requests.packages.urllib3.exceptions import InsecureRequestWarning
requests.packages.urllib3.disable_warnings(InsecureRequestWarning)

from f5.bigip import ManagementRoot

# Connect to the BigIP and configure the basic objects
mgmt = ManagementRoot("IP", "admin", "pw")

mypool = mgmt.tm.ltm.pools.pool.create(name='mypool' , partition='Common')

Here's the error's I'm seeing.

Traceback (most recent call last):
  File "C:\python\test3.py", line 11, in <module>
    mypool = mgmt.tm.ltm.pools.pool.create(name='mypool' , partition='Common')
  File "C:\Users\dave\AppData\Local\Programs\Python\Python36-32\lib\site-pack
ages\f5\bigip\resource.py", line 933, in create
    return self._create(**kwargs)
  File "C:\Users\dave\AppData\Local\Programs\Python\Python36-32\lib\site-pack
ages\f5\bigip\resource.py", line 887, in _create
    kwargs = self._check_for_python_keywords(kwargs)
  File "C:\Users\dave\AppData\Local\Programs\Python\Python36-32\lib\site-pack
ages\f5\bigip\resource.py", line 459, in _check_for_python_keywords
    for key, val in kwargs.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

**Comment by jasonrahm** [comment] 2017-01-06 15:02
iteritems is  a 2.x remnant, I don't think it exists in 3.x. @caphrim007 as this is in the resource (and also in the todict mixin) it's a much larger issue than just the pool.

**Comment by caphrim007** [comment] 2017-01-06 15:07
@jasonrahm yes, this method should be using the iteritems() method provided by the six library as is done in other areas of the sdk

**Comment by caphrim007** [comment] 2017-01-06 15:34
@KDaveC this bug is now fixed.

To answer the original question, the available resources for help are

- this github repo for bugs and feature reqs
- the docs at http://f5-sdk.readthedocs.io/en/latest/
- the openstack slack team https://f5-openstack-slack.herokuapp.com/

**Comment by caphrim007** [comment] 2017-01-06 15:36
and one final note, python3 support is still a work-in-progress. So there is the chance (as you've seen here) that there are still bugs in it.

Here's the bug tracking py3 support

https://github.com/F5Networks/f5-common-python/issues/287

**Comment by jasonrahm** [comment] 2017-01-06 15:49
@KDaveC I plan to write a series of articles on using the sdk, what topics would be most helpful to you?

**Comment by KDaveC** [comment] 2017-01-06 16:31
Thank you for the quick responses. Sorry, another noob question. How do I go about getting the update. I tried pip with -U and it said everything was up-to-date.

As for articles there are a lot of us out there that did not take any or very little programming in school so anything that better explains how to get started. A lot of the fundamentals are foreign especially with respect to object oriented languages. I also noticed that a lot is written for Python2 and of course someone just starting out is going to learn version 3 so it would be helpful to note where things might be different.

**Comment by jasonrahm** [comment] 2017-01-06 16:44
the update is on our development train, so you would need to clone from here until our next release. re: articles, I'll try and write them for 2.x and 3.x, which will be good for me since I haven't touched 3.x yet.

**Comment by caphrim007** [comment] 2017-01-06 16:45
@KDaveC the command to update your local code from the development code where we made the change is the following

`pip install --upgrade git+https://github.com/F5Networks/f5-common-python.git`

**Comment by KDaveC** [comment] 2017-01-06 18:13
@caphrim007 I'm using Windows 7 and found that I could get that to run when removing the +.  
pip install --upgrade git https://github.com/F5Networks/f5-common-python.git 

It downloads but then I get another error. Cannot determine archive format of C:\Users\dave\AppData\Local\Temp\pip-7p6uhza7-build

**Comment by caphrim007** [comment] 2017-01-06 18:17
@KDaveC the + is required or else pip does not know how to process it.

**Comment by KDaveC** [comment] 2017-01-06 19:23
@caphrim007 I tried that first and got the below error.
  Error [WinError 2] The system cannot find the file specified while executing c
ommand git clone -q https://github.com/F5Networks/f5-common-python.git C:\Users\
dave\AppData\Local\Temp\pip-79p0l_pn-build
Cannot find command 'git'

**Comment by caphrim007** [comment] 2017-01-06 23:44
@KDaveC The error says exactly what the problem is

"Cannot find command git"

You need git installed to get code from github

https://git-scm.com/download/win

**Comment by KDaveC** [comment] 2017-01-07 18:10
Thank you very much. Once again not being a developer the fundamentals are often missing. I got it updated and all the basics seem to be working now. I did find one more possible issue. When printing a description for a pool with a null value I get an error. I verified that the value didn't exist with print (pool_1.raw)

print (pool_1.description)

Traceback (most recent call last):
  File "<pyshell#10>", line 1, in <module>
    print (pool_1.description)
  File "C:\Users\A465286\AppData\Local\Programs\Python\Python36-32\lib\site-packages\f5\bigip\mixins.py", line 127, in __getattr__
    raise AttributeError(error_message)
AttributeError: '<class 'f5.bigip.tm.ltm.pool.Pool'>' object has no attribute 'description'

**Comment by caphrim007** [comment] 2017-01-07 19:55
This is expected behavior as this is how all python objects work, and the f5 sdk works with python objects.

You would receive the same error if you were to do the following in plain python

```
class foo(object): pass
ok = foo()
print ok.bar
```

Insofar as it would raise an attribute error.

```AttributeError: 'foo' object has no attribute 'bar'```

So this is not a bug. You can handle it in one of several ways.

1. use hasattr() before you reference the attribute to see if the attribute exists

```
if hasattr(pool, 'description'):
   print pool.description
```

2. Do the print in a try block

```
try:
    print pool.description
except AttributeError:
    pass
```

3. Use the dictionary keys of the object with a default value specified. This requires converting the object to a dictionary using the to_dict() method, and then using the get() method on that dictionary. The first value to .get() is the keyyou want to get, and the second value is what you want returned if that key does not exist.

```
description = pool.to_dict().get('description', None)
```

Hope that helps.

**Comment by KDaveC** [comment] 2017-01-09 13:30
Thank you again for the information. This should be a enough to keep me busy for a while..

**Closed as completed** 2017-01-09 16:54 UTC
Labels: bug
