### ISSUE TITLE
The Resource `create` and `load` Aliasing Issue

### ISSUE THREAD

**Issue by zancas** [F5Networks/f5-common-python#411] opened 2016-05-12 16:17 UTC
`Resource` `create` and `load` create 2 aliases for the same object in the callers namespace, _IF_ they're called on the right hand side of an assignment statement.

This leads to confusing errors like this:

https://github.com/F5Networks/f5-common-python/issues/407

This "design" issue is being created to provide a single location to discuss the problem and come up with fix.

**Comment by zancas** [comment] 2016-05-12 16:18
I'll add proposed fixes to this thread next time I think about it.

**Comment by wojtek0806** [comment] 2016-05-19 08:59
Issue Review: Has this been resolved with #414 PR? If so we can close it. Also this seems like duplicate of #415

**Comment by zancas** [comment] 2016-05-19 15:44
They're similar, but not duplicate.

**Comment by pjbreaux** [comment] 2016-06-14 15:31
Punting to you @zancas

**Comment by zancas** [comment] 2016-06-21 18:12
@pjbreaux can you please open a PR from the branch you're using for this to development?  That way we can gather our comments and code into one place.

**Closed as completed** 2016-06-30 19:52 UTC
Labels: enhancement, critical, bugfix, DESIGN
